export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const SET_FAVORITES = "SET_FAVORITES";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
