export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const OPEN_SIGNUP_MODAL = "OPEN_SIGNUP_MODAL";
export const OPEN_SIGNIN_MODAL = "OPEN_SIGNIN_MODAL";
export const OPEN_ADD_FUNDS_MODAL = "OPEN_ADD_FUNDS_MODAL";
export const OPEN_WITHDRAW_FUNDS_MODAL = "OPEN_WITHDRAW_FUNDS_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const ADD_FUNDS = "ADD_FUNDS";
export const WITHDRAW_FUNDS = "WITHDRAW_FUNDS";

export const SET_CATEGORY = "SET_CATEGORY";
export const SET_SUBCATEGORY = "SET_SUBCATEGORY";
