export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const OPEN_SIGNUP_MODAL = "OPEN_SIGNUP_MODAL";
export const OPEN_SIGNIN_MODAL = "OPEN_SIGNIN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const ADD_FUNDS = "ADD_FUNDS";
export const WITHDRAW_FUNDS = "WITHDRAW_FUNDS";

export const SET_FAVORITES = "SET_FAVORITES";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";

export const SET_CATEGORY = "SET_CATEGORY";
export const SET_SUBCATEGORY = "SET_SUBCATEGORY";
